# Generated by Django 3.0.8 on 2021-01-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('emer_reasoning', models.CharField(choices=[('breathing', 'breathing'), ('fatal-wounds', 'fatal-wounds'), ('coma', 'coma'), ('shock', 'Signs of Shock'), ('dehydration', 'Severe Signs of Dehydration'), ('other', 'Other')], max_length=15)),
                ('extra_information', models.TextField()),
                ('hospital_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_patient', to='hospital.HospitalArea')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('emer_reasoning', models.CharField(choices=[('sick', 'Sick'), ('temperature', 'Temperature'), ('cut', 'Cut'), ('trauma', 'Trauma'), ('poisoning', 'Poisoning'), ('burns', 'Burns'), ('other', 'Other')], max_length=11)),
                ('cut_location', models.CharField(blank=True, choices=[('head', 'Head'), ('torso', 'Torso'), ('arms', 'Arms'), ('legs', 'Legs')], max_length=5, null=True)),
                ('extra_information', models.TextField()),
                ('hospital_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.HospitalArea')),
            ],
        ),
    ]
