# Generated by Django 3.0.8 on 2021-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prioritypatient',
            name='current_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
