# Generated by Django 3.0.8 on 2021-01-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210116_1656'),
        ('patient', '0003_auto_20210116_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emer_reasoning',
            new_name='reasoning',
        ),
        migrations.AlterField(
            model_name='patient',
            name='extra_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prioritypatient',
            name='extra_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prioritypatient',
            name='hospital_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_patients', to='hospital.PriorityHospitalArea'),
        ),
    ]
