# Generated by Django 3.0.8 on 2021-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210116_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
