# Generated by Django 3.0.8 on 2021-01-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('resusciation', 'Resusciation Area'), ('trauma', 'Major Wound'), ('minor-procedure', 'Major Procedure'), ('consultation', 'Consultation'), ('network', 'Network')], max_length=16)),
            ],
        ),
    ]
