# Generated by Django 3.0.8 on 2021-01-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210116_0649'),
        ('patient', '0002_auto_20210116_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital.HospitalArea'),
        ),
        migrations.AlterField(
            model_name='prioritypatient',
            name='hospital_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_patients', to='hospital.PriorityHospitalArea'),
        ),
    ]
