# Generated by Django 3.0.8 on 2021-01-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210116_1722'),
        ('patient', '0004_auto_20210116_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital.HospitalArea'),
        ),
    ]
