# Generated by Django 3.0.8 on 2021-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalarea',
            name='area',
            field=models.CharField(choices=[('resusciation', 'Resusciation Area'), ('trauma', 'Major Wound'), ('major-procedure', 'Major Procedure'), ('consultation', 'Consultation'), ('network', 'Network')], max_length=16),
        ),
    ]
