# Generated by Django 3.0.8 on 2021-01-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210116_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityHospitalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('resusciation', 'Resusciation Area'), ('trauma', 'Major Wound')], max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='hospitalarea',
            name='area',
            field=models.CharField(choices=[('minor-procedure', 'Minor Procedure'), ('consultation', 'Consultation'), ('network', 'Network')], max_length=16),
        ),
    ]
