# Generated by Django 3.0.8 on 2021-01-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210116_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityhospitalarea',
            name='area',
            field=models.CharField(choices=[('resusciation', 'Resusciation Area'), ('major-wound', 'Major Wound')], max_length=16),
        ),
    ]
