# Generated by Django 3.0.8 on 2021-01-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210116_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityhospitalarea',
            name='area',
            field=models.CharField(choices=[('Resusciation Area', 'Resusciation Area'), ('Major Wound', 'Major Wound')], max_length=18),
        ),
    ]
