# Generated by Django 3.0.8 on 2021-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210116_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalarea',
            name='area',
            field=models.CharField(choices=[('Minor Procedure Area', 'Minor Procedure Area'), ('Consultation Area', 'Consultation Area'), ('Online Area', 'Online Area')], max_length=23),
        ),
    ]
